#url = https://www.saucedemo.com
#username = standard_user
#password = secret_sauce
#firstname = Ahmed
#lastname = Koryem
#postalCode = 15448
#browser = chrome
#invalidusername = stdard_user
#invalidpassword  = secret_sauce
#emptypostalCode=
#emptyfirstname=
#emptylastname=